---
- hosts: localhost

  vars:
    vault_url: "https://vaultdev.in.neoncorp.com.br:8200/"
    vault_path: "sec-certificates/data/"
    secret_name: "cloud.campanha.meifacil.com"
    url: "https://api.azionapi.net/digital_certificates"
    update_cert_id: 
    headers: "33139"
      Accept: "application/json; version=3"
      Authorization: "Token {{ ACCESS_TOKEN }}"
      Content-Type: "application/json"

  vars_files:
    - vault.yml

  tasks:

# #######################  RESGATANDO CERTIFICADO NO VAULT E CONFIGURANDO NO AWS ACM  ############################

    - name: "Recuperando credencial no Vault"
      community.hashi_vault.vault_read:
        url: "https://vault.com.br:8200/"
        path: "{{vault_path}}{{ secret_name }}"
        auth_method: ldap
        username: "{{ vault_user }}"
        password: "{{ vault_password }}"
      become: no
      delegate_to: localhost
      register: secret
      #no_log: true

    - name: Import new certificate request
      uri:
        url: "{{ url }}"
        method: POST
        headers: "{{ headers }}"
        body_format: json
        body:
          name: "{{ secret_name }}"
          certificate: "{{ secret.data.data.data.public_key }}"
          private_key: "{{ secret.data.data.data.private_key }}"
      register: response
      failed_when: response.status != 201
      timeout: 30
      
    - name: Update new certificate request
      uri:
        url: "{{ url }}/{{ update_cert_id }}"
        method: PUT
        headers: "{{ headers }}"
        body_format: json
        body:
          name: "{{ secret_name }}__2024"
          certificate: "{{ secret.data.data.data.public_key }}"
          private_key: "{{ secret.data.data.data.private_key }}"
      register: response
      failed_when: response.status != 201
      timeout: 30
